// site copy — every translatable string, keyed by [data-i18n] names
export const STRINGS = {
  es: {
    // meta
    "meta.description":
      "Cielo Negro — el nuevo álbum de Santo Vøid. 8 canciones. Estática Records, 2026.",
    "meta.title.home": "Santo Vøid — Cielo Negro",
    "meta.title.tracklist": "Tracklist — Cielo Negro | Santo Vøid",
    "meta.title.track": "Cielo Negro | Santo Vøid",
    "meta.title.studio": "Estudio — Cielo Negro | Santo Vøid",
    "meta.title.contact": "Contacto — Santo Vøid",

    // nav + menu
    "nav.switch": "Cambiar idioma",
    "menu.open": "Abrir menú",
    "menu.home": "Inicio",
    "menu.studio": "Estudio",
    "menu.tracklist": "Tracklist",
    "menu.single": "Single",
    "menu.contact": "Contacto",
    "menu.footer.studio": "Entrar al estudio",
    "menu.footer.contact": "Booking",

    // shared footer
    "footer.edition": "Cielo Negro __ 2026",
    "footer.label": "[ Estática Records ]",

    // home
    "preloader.loading": "Cargando",
    "preloader.boot": "Cielo Negro — Encendiendo",
    "home.subtitle": "El nuevo álbum de Santo Vøid",
    "home.release": "Sale __ 13.11.26",
    "home.meta": "[ 8 canciones — Estática Records ]",
    "home.specs": "08 canciones / 27:48",
    "home.scroll": "Desliza",
    "home.manifesto.label": "(01) — Manifiesto",
    "home.manifesto":
      'Ocho canciones escritas entre las 2 y las 6 de la mañana <span class="inline-img" data-img="shoot/gallery-2.jpg"></span> con la ciudad dormida y las pantallas encendidas. Un disco sobre los que no duermen, sobre lo que se rompe <span class="inline-img" data-img="shoot/gallery-3.jpg"></span> y sobre la luz que queda cuando todo se apaga.',
    "home.manifesto.meta.1": "Trap oscuro",
    "home.manifesto.meta.2": "Grabado en CDMX",
    "home.manifesto.meta.3": "Once meses de noches",
    "home.tracks.label": "(02) — Tracklist",
    "home.tracks.title": "Ocho canciones, una sola noche",
    "home.tracks.all": "Ver el tracklist completo",
    "home.artist.label": "(03) — El artista",
    "home.artist.bio":
      "Santo Vøid creció en Iztapalapa y aprendió a producir en una laptop prestada. Después de dos mixtapes que circularon de mano en mano, Cielo Negro es su primer álbum: once meses encerrado, ocho canciones y ninguna concesión.",
    "home.artist.cta": "Entrar al estudio",
    "home.release.label": "(04) — Lanzamiento",
    "home.release.title": "Sale el 13.11.26",
    "home.release.days": "Días",
    "home.release.hours": "Horas",
    "home.release.minutes": "Min",
    "home.release.seconds": "Seg",
    "home.release.out": "Ya disponible",
    "home.release.presave": "Pre-guardar",
    "home.release.note":
      "En todas las plataformas. Vinilo azul de edición limitada, 300 copias numeradas.",
    "home.marquee": "Cielo Negro ✦ 13.11.26 ✦ Estática Records ✦ Santo Vøid ✦",

    // sound + cursor
    "sound.label": "Sonido",
    "sound.toggle": "Activar o silenciar el sonido",
    "preloader.enter.sound": "Entrar con sonido",
    "preloader.enter.mute": "Sin sonido",
    "preloader.enter.hint": "Mejor con audífonos",
    "cursor.view": "Ver",

    // tracklist
    "tracklist.meta.left": "[ Cielo Negro ]",
    "tracklist.meta.right": "/ 8 canciones — 27:48",

    // track
    "track.feat": "Con",
    "track.producer": "Producción",
    "track.written": "Letra",
    "track.mix": "Mezcla",
    "track.recorded": "Grabada en",
    "track.length": "Duración",
    "track.tempo": "Tempo",
    "track.key": "Tonalidad",
    "track.next": "Siguiente",
    "track.none": "—",

    // studio
    "studio.title": "Estudio",
    "studio.subtitle": "Detrás de Cielo Negro",
    "studio.about.1":
      "Cielo Negro se escribió de noche. Once meses encerrados en un cuarto sin ventanas, con las luces apagadas y solo el brillo azul de las pantallas. Cada canción empezó como una nota de voz a las tres de la mañana y terminó como una confesión.",
    "studio.about.2":
      "El sonido es trap oscuro, pero crudo: 808s que distorsionan a propósito, voces grabadas en una sola toma y silencios que pesan tanto como los versos. Nada se pulió de más. Lo que se rompió, se dejó roto. El resultado es un disco sobre la ciudad cuando nadie la mira, sobre los que no duermen y sobre la luz que queda cuando todo se apaga.",
    "studio.pie.header": "Todo se grabó entre las 2 y las 6 de la mañana.",
    "studio.pie.left": "[ Sesión 01 ]",
    "studio.pie.right": "__ Estudio B, CDMX",
    "studio.stats.title": "En números",
    "studio.stats.copy":
      "Lo que costó hacer Cielo Negro, contado sin filtro.",
    "studio.stat.1": "meses de noches en vela entre la primera nota y el master final",
    "studio.stat.1.info": "Proceso",
    "studio.stat.2": "beats descartados antes de encontrar el sonido del disco",
    "studio.stat.2.info": "Producción",
    "studio.stat.3": "invitados: Nyx Rivera, Lía Ceniza y Duke Ølvido",
    "studio.stat.3.info": "Colaboraciones",
    "studio.stat.4": "toma por voz. Sin comping, sin trucos, sin repetir",
    "studio.stat.4.info": "Grabación",
    "studio.credits": "Créditos",

    // contact
    "contact.time": "Hora local",
    "contact.base": "Base",
    "contact.base.value": "Ciudad de México",
    "contact.booking": "Booking",
    "contact.press": "Prensa",
    "contact.press.value": "prensa@santovoid.com",
    "contact.label": "Sello",
    "contact.management": "Management",
    "contact.merch": "Merch",
    "contact.merch.value": "Próximamente",
    "contact.voice": "Línea directa",
  },

  en: {
    "meta.description":
      "Cielo Negro — the new album by Santo Vøid. 8 tracks. Estática Records, 2026.",
    "meta.title.home": "Santo Vøid — Cielo Negro",
    "meta.title.tracklist": "Tracklist — Cielo Negro | Santo Vøid",
    "meta.title.track": "Cielo Negro | Santo Vøid",
    "meta.title.studio": "Studio — Cielo Negro | Santo Vøid",
    "meta.title.contact": "Contact — Santo Vøid",

    "nav.switch": "Switch language",
    "menu.open": "Open menu",
    "menu.home": "Home",
    "menu.studio": "Studio",
    "menu.tracklist": "Tracklist",
    "menu.single": "Single",
    "menu.contact": "Contact",
    "menu.footer.studio": "Enter the studio",
    "menu.footer.contact": "Booking",

    "footer.edition": "Cielo Negro __ 2026",
    "footer.label": "[ Estática Records ]",

    "preloader.loading": "Loading",
    "preloader.boot": "Cielo Negro — Powering up",
    "home.subtitle": "The new album by Santo Vøid",
    "home.release": "Out __ 11.13.26",
    "home.meta": "[ 8 tracks — Estática Records ]",
    "home.specs": "08 tracks / 27:48",
    "home.scroll": "Scroll",
    "home.manifesto.label": "(01) — Manifesto",
    "home.manifesto":
      'Eight songs written between 2 and 6 in the morning <span class="inline-img" data-img="shoot/gallery-2.jpg"></span> with the city asleep and the screens still on. A record about the ones who don\'t sleep, about what breaks <span class="inline-img" data-img="shoot/gallery-3.jpg"></span> and about the light that\'s left when everything goes dark.',
    "home.manifesto.meta.1": "Dark trap",
    "home.manifesto.meta.2": "Recorded in CDMX",
    "home.manifesto.meta.3": "Eleven months of nights",
    "home.tracks.label": "(02) — Tracklist",
    "home.tracks.title": "Eight songs, one long night",
    "home.tracks.all": "See the full tracklist",
    "home.artist.label": "(03) — The artist",
    "home.artist.bio":
      "Santo Vøid grew up in Iztapalapa and learned to produce on a borrowed laptop. After two mixtapes passed from hand to hand, Cielo Negro is his first album: eleven months locked in, eight songs and zero compromises.",
    "home.artist.cta": "Enter the studio",
    "home.release.label": "(04) — Release",
    "home.release.title": "Out 11.13.26",
    "home.release.days": "Days",
    "home.release.hours": "Hours",
    "home.release.minutes": "Min",
    "home.release.seconds": "Sec",
    "home.release.out": "Out now",
    "home.release.presave": "Pre-save",
    "home.release.note":
      "On every platform. Limited blue vinyl edition, 300 numbered copies.",
    "home.marquee": "Cielo Negro ✦ 11.13.26 ✦ Estática Records ✦ Santo Vøid ✦",

    "sound.label": "Sound",
    "sound.toggle": "Toggle sound",
    "preloader.enter.sound": "Enter with sound",
    "preloader.enter.mute": "Without sound",
    "preloader.enter.hint": "Best with headphones",
    "cursor.view": "View",

    "tracklist.meta.left": "[ Cielo Negro ]",
    "tracklist.meta.right": "/ 8 tracks — 27:48",

    "track.feat": "Featuring",
    "track.producer": "Produced by",
    "track.written": "Written by",
    "track.mix": "Mixed by",
    "track.recorded": "Recorded at",
    "track.length": "Length",
    "track.tempo": "Tempo",
    "track.key": "Key",
    "track.next": "Next",
    "track.none": "—",

    "studio.title": "Studio",
    "studio.subtitle": "Behind Cielo Negro",
    "studio.about.1":
      "Cielo Negro was written at night. Eleven months locked in a windowless room, lights off, nothing but the blue glow of the screens. Every song started as a 3am voice memo and ended up as a confession.",
    "studio.about.2":
      "The sound is dark trap, but raw: 808s that distort on purpose, vocals cut in a single take and silences that weigh as much as the verses. Nothing was over-polished. What broke stayed broken. The result is a record about the city when nobody is watching, about the ones who don't sleep, and about the light that's left when everything goes dark.",
    "studio.pie.header": "Everything was recorded between 2 and 6 in the morning.",
    "studio.pie.left": "[ Session 01 ]",
    "studio.pie.right": "__ Studio B, CDMX",
    "studio.stats.title": "By the numbers",
    "studio.stats.copy": "What it took to make Cielo Negro, counted without a filter.",
    "studio.stat.1": "months of sleepless nights between the first note and the final master",
    "studio.stat.1.info": "Process",
    "studio.stat.2": "beats thrown away before finding the sound of the record",
    "studio.stat.2.info": "Production",
    "studio.stat.3": "guests: Nyx Rivera, Lía Ceniza and Duke Ølvido",
    "studio.stat.3.info": "Features",
    "studio.stat.4": "take per vocal. No comping, no tricks, no second tries",
    "studio.stat.4.info": "Recording",
    "studio.credits": "Credits",

    "contact.time": "Local time",
    "contact.base": "Based in",
    "contact.base.value": "Mexico City",
    "contact.booking": "Booking",
    "contact.press": "Press",
    "contact.press.value": "press@santovoid.com",
    "contact.label": "Label",
    "contact.management": "Management",
    "contact.merch": "Merch",
    "contact.merch.value": "Coming soon",
    "contact.voice": "Direct line",
  },
};

// credits list on the studio page — names stay, roles translate
export const CREDITS = [
  { name: "Santo Vøid", role: { es: "Voz, letras, producción", en: "Vocals, lyrics, production" } },
  { name: "Kaelo", role: { es: "Producción ejecutiva", en: "Executive production" } },
  { name: "Mørk", role: { es: "Producción, 808s", en: "Production, 808s" } },
  { name: "Fantasma 808", role: { es: "Producción, sintetizadores", en: "Production, synths" } },
  { name: "Nyx Rivera", role: { es: "Voz invitada — Humo", en: "Guest vocals — Humo" } },
  { name: "Lía Ceniza", role: { es: "Voz invitada — Fantasmas", en: "Guest vocals — Fantasmas" } },
  { name: "Duke Ølvido", role: { es: "Voz invitada — Neón", en: "Guest vocals — Neón" } },
  { name: "Iván Cruz", role: { es: "Mezcla", en: "Mixing" } },
  { name: "Renata Solís", role: { es: "Masterización", en: "Mastering" } },
  { name: "Estudio B", role: { es: "Grabación, CDMX", en: "Recording, CDMX" } },
  { name: "Cuarto Oscuro", role: { es: "Grabación adicional", en: "Additional recording" } },
  { name: "Leo Tamez", role: { es: "Ingeniería de grabación", en: "Recording engineer" } },
  { name: "Maya Ortega", role: { es: "Asistente de ingeniería", en: "Assistant engineer" } },
  { name: "Ximena Vale", role: { es: "Dirección creativa", en: "Creative direction" } },
  { name: "Bruno Lara", role: { es: "Fotografía", en: "Photography" } },
  { name: "Ana Villa", role: { es: "Dirección de arte", en: "Art direction" } },
  { name: "Tomás Ríos", role: { es: "Diseño gráfico", en: "Graphic design" } },
  { name: "Sofía Mena", role: { es: "Estilismo", en: "Styling" } },
  { name: "Unidad 9", role: { es: "Visuales en vivo", en: "Live visuals" } },
  { name: "Nora Beltrán", role: { es: "Management", en: "Management" } },
  { name: "Diego Paz", role: { es: "Booking", en: "Booking" } },
  { name: "Estática Records", role: { es: "Sello", en: "Label" } },
  { name: "Carla Ibáñez", role: { es: "A&R", en: "A&R" } },
  { name: "Hugo Márquez", role: { es: "Prensa", en: "Press" } },
  { name: "Lucía Ferro", role: { es: "Redes", en: "Social media" } },
  { name: "Rafa Soto", role: { es: "Merch", en: "Merch" } },
  { name: "Pablo Ceja", role: { es: "Web", en: "Web" } },
  { name: "Mamá", role: { es: "Todo lo demás", en: "Everything else" } },
];
